# Generated by Django 4.2.7 on 2025-11-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS irish_counties_geom_gist_idx ON irish_counties USING GIST (geom);",
            reverse_sql="DROP INDEX IF EXISTS irish_counties_geom_gist_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS carwash_point_gist_idx ON carwash USING GIST (wkb_geometry);",
            reverse_sql="DROP INDEX IF EXISTS carwash_point_gist_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS population_points_point_gist_idx ON population_points USING GIST (wkb_geometry);",
            reverse_sql="DROP INDEX IF EXISTS population_points_point_gist_idx;"
        ),
    ]
